Improve backup/restore db
craftercms/craftercms pull request #4410
Opened 2020-11-13 23:04 UTC by jdrossl

#4295

2020-11-19 14:31 UTC, sumerjabri requested changes

2020-11-19 15:06 UTC, jdrossl commented on downloads.gradle
> +            src "https://raw.githubusercontent.com/vishnubob/wait-for-it/master/wait-for-it.sh"
I did it this way because they don't even have versions, the only option would be to copy the file to our repo and manually upgrade if needed

2020-11-20 21:02 UTC, sumerjabri commented on downloads.gradle
> +            src "https://raw.githubusercontent.com/vishnubob/wait-for-it/master/wait-for-it.sh"
I'm okay with copying the file to our repo.

2020-11-30 17:51 UTC, avasquez614 requested changes
The wait for it script needs to be copied to the repo instead of downloading it.

2020-12-01 17:05 UTC, sumerjabri approved these changes

2020-12-01 17:06 UTC, sumerjabri commented
@jdrossl Please fix the conflict.

2020-12-02 19:49 UTC, merged