Add directory watcher dependency
craftercms/craftercms pull request #6230
Opened 2023-09-25 11:36 UTC by phuongnq

### Ticket reference or the full description of what's in the PR
[feature/craftercms-6223](https://github.com/craftercms/craftercms/issues/6223)

2023-09-28 13:52 UTC, sumerjabri requested changes

2023-09-28 13:52 UTC, sumerjabri commented on pom.xml
> +		<directoryWatcher.version>0.18.0</directoryWatcher.version>
directory-watcher.version

2023-10-02 09:26 UTC, phuongnq commented on pom.xml
> +		<directoryWatcher.version>0.18.0</directoryWatcher.version>
Updated. Thank you!

2023-10-02 20:40 UTC, sumerjabri approved these changes

2023-10-03 18:05 UTC, merged