Add rootless docker images
craftercms/craftercms pull request #6927
Opened 2024-06-05 07:50 UTC by phuongnq

### Ticket reference or the full description of what's in the PR

2024-06-05 14:50 UTC, sumerjabri requested changes

2024-06-05 14:50 UTC, sumerjabri commented on resources/docker/images/authoring/tomcat/docker-entrypoint.sh
> +run_as_crafter() {
Please rename this to `run_as` since it's not always `crafter`. Please do this for all files as needed.

2024-06-05 15:08 UTC, avasquez614 approved these changes

2024-06-06 02:51 UTC, phuongnq commented on resources/docker/images/authoring/tomcat/docker-entrypoint.sh
> +run_as_crafter() {
Updated to `run_as`

2024-06-07 00:26 UTC, sumerjabri approved these changes

2024-06-07 00:26 UTC, merged